Store artifacts longer. It was causing issues when a build was starting. Then, in parallel, a new source started. the old second build could not find the previous artifacts and was causing some wierd errors like:
Running as SYSTEM
Construction à distance sur blade03 (i386 amd64) in workspace <https://llvm-jenkins.debian.net/job/llvm-toolchain-stretch-12-binaries/architecture=amd64,distribution=stretch,label=amd64/ws/>
[WS-CLEANUP] Deleting project workspace...
[WS-CLEANUP] Deferred wipeout is used...
ERROR: Failed to copy artifacts from llvm-toolchain-stretch-12-source with filter: *
Archiving artifacts
Enregistrement des résultats des tests
ERROR: Step ‘Publier le rapport des résultats des tests JUnit’ failed: No test report files were found. Configuration error?